### PR TITLE
Couple oxidized CH4 into CO2 cycle

### PR DESCRIPTION
**Pull request by FrankErrickson**
This adds the additional CO2 emissions from oxidized CH4 to total CO2 emissions in the carbon cycle component.

### CODE REVIEW

**Comment by FrankErrickson** [comment]
@kar5469 Can you take a look at this to make sure I coupled the oxidized CH4 into the carbon cycle properly.  Also, if you want to look at the equation in the carbon cycle that converts oxidized CH4 into GtC units, that'd be great too.

**Comment by kar5469** [comment]
hey! I went over the ch4_cycle.jl
In 31: Check the timestep, should be t-1 for natural emissions.  emiss_prev = p.fossil_emiss_CH₄[t-1] + p.natural_emiss_CH₄[**t-1**]

Otherwise, it looks fine to me.

**Comment by FrankErrickson** [comment]
> hey! I went over the ch4_cycle.jl
> In 31: Check the timestep, it should be t-1 for natural emissions. emiss_prev = p.fossil_emiss_CH₄[t-1] + p.natural_emiss_CH₄[**t-1**]

This actually follows the FAIR equations. They don't use a `t-1` timestep for the natural emissions. I copied that since this is supposed to be an exact replication of the Python version. See the Python version of this line here: [FAIR methane cycle code](https://github.com/OMS-NetZero/FAIR/blob/916265bd3a94a2592fa2605c6c8e0e110d4083fc/fair/forward.py#L665)

> Is there a place in the co2_cycle.jl where the oxidized emissions are added to the fossil co2 emissions? I'm having trouble finding that line that takes in **oxidised_CH₄_GtC **

You can see the changes I made at this commit: [commit that couples oxidized CH4 to carbon cycle](https://github.com/anthofflab/MimiFAIR.jl/pull/32/commits/ddd73067764d5c84cc5f54d8cbb2ed7c4348c747). These changes aren't in the main (master) FAIR code yet. If you are looking at all of the model code, make sure you are on the `couple_oxidized_ch4` branch. There's a little pull down tab near the top of the main page for this repository. But in this branch's `co2_cycle.jl` file, I create a variable that adds oxidized CH4 (in GtC units) to the RCP CO2 emissions.

**Comment by kar5469** [comment]
Thanks! Now I see where the emissions are being added together. It looks correct! 
And, I understand that your making the replica with the python code for the natural emissions. To me, it just looks like another possible error on their end to say "previous emissions".

We'll have to make these same changes to the v.oxidised_CH₄ in the [Fair-ch4-paper repository](https://github.com/FrankErrickson/FAIR-CH4-Paper/tree/master/src/create_models/additional_model_components) for my new methane model with feedbacks.

**Comment by FrankErrickson** [comment]
@davidanthoff Any thoughts on this `t-1` issue for the natural emissions? I just replicated what the FAIR code does so our results matched and we could test against the output from the Python version. The FAIR developers said they were holding off until FAIR v2.0 to deal with some of these methane cycle issues, so not sure they'd want to hear about another potential issue from me.

**Comment by davidanthoff** [comment]
For CO2 I would probably say that something like this timestep issue is certainly not ideal (because you are essentially using a different way to discretize your continuous time process to discrete time there), but in terms of results it probably wouldn't make much of a difference, so I wouldn't worry so much. But with CH4 and its much shorter lifetime, I'm not so sure... Could we run with both options once and see whether it makes a difference for our results? If it doesn't, then I'd be tempted to keep the code in line with the original Python code, and try to work with the upstream team to change this in some future version. If it does make a difference for our results, we should probably reconsider...

**Comment by kar5469** [comment]
Hi David and Frank, sorry for the delayed reply! I checked to see if the timestep issue for the natural emissions made an important impact on the results. Like we guessed, the differences are miniscule. For methane, concentrations differ up to 5 ppb in a single year. And for nitrous oxide, concentrations differ up to 0.3 ppb. Global temperature differs up to 0.0012 K. Plus, the natural emissions are held constant after 2005 so the timestep becomes less important as it reads in the same number at each step.

**Comment by FrankErrickson** [comment]
> Hi David and Frank, sorry for the delayed reply! I checked to see if the timestep issue for the natural emissions made an important impact on the results. Like we guessed, the differences are miniscule. For methane, concentrations differ up to 5 ppb in a single year. And for nitrous oxide, concentrations differ up to 0.3 ppb. Global temperature differs up to 0.0012 K. Plus, the natural emissions are held constant after 2005 so the timestep becomes less important as it reads in the same number at each step.

@davidanthoff Given that the timestep issue doesn't have a large effect, can you review/accept this pull request? That will let us move forward with all of the other code and get some final results to circulate. We can always revisit the timestep issue with a different PR.

**Comment by kar5469** [comment]
@davidanthoff 
Can you review/accept this pull request? Thanks in advance!

**Comment by lrennels** [comment]
@FrankErrickson I can help try to get this merged for you!  One thing I do foresee @davidanthoff asking about is why the tests are now failing though, is that expected?

These tests fail:

```
# Load Python version of FAIR output.
python_co2_conc      = DataFrame(load(joinpath(@__DIR__, "..", "data", "validation_data", "rcp85_python_fair_concentrations.csv"))).co2
python_temperature   = DataFrame(load(joinpath(@__DIR__, "..", "data", "validation_data", "rcp85_python_fair_temperature.csv"))).temperature

# Run tests for global temperature anomaly and atmospheric CO₂ concentrations.
@test m[:co2_cycle, :C]            ≈ python_co2_conc atol = Precision
@test m[:temperature, :T]          ≈ python_temperature atol = Precision
```

and when I run it the maximum difference between paired Python outputs for `:C` was 23 and for `:T` was 0.03.  Do you expect the values to be different from Python?

**Review by lrennels — APPROVED** [review]

**Review by lrennels — DISMISSED** [review]

**Comment by FrankErrickson** [comment]
@lrennels Yea, 5-second version of everything is there was a bug in the original Python FAIR code, and we are fixing that here. But now the testing data (based on the old, incorrect version of FAIR), is out of sync with the fixed Mimi code.

I think the FAIR team is focused more on getting out FAIR v2.0, so not sure if they are going to fix things on their end so everything can sync up again. But at this point to get the tests passing, I'd have to fix the Python version too, run it to get new testing data, and then update that.

**Comment by lrennels** [comment]
@FrankErrickson that makes sense, merging might be blocked until all tests pass (and it looks like maybe only @davidanthoff can approve this but I'm trying!), so I would just comment out those tests for now if that's the team priority.  THat's above my pay grade so David may disagree :)

**Review by lrennels — APPROVED** [review]

**Pull request merged**
